elastic/beats-tester

.gitignore, roles/common/tasks/download.yml, roles/common/tasks/main.yml, roles/common/vars/main.yml, roles/test-install/tasks/main.yml, roles/test-uninstall/tasks/main.yml, roles/test-win-packetbeat-file/files/run_script.ps1, roles/test-win-packetbeat-file/files/sleep.ps1, roles/test-win-packetbeat-file/tasks/main.yml, roles/test-win-topbeat-file/files/replace.ps1, roles/test-win-topbeat-file/files/run_script.ps1, roles/test-win-topbeat-file/files/sleep.ps1, roles/test-win-topbeat-file/files/topbeat.yml, roles/test-win-topbeat-file/tasks/main.yml, run-settings-nightly.yml, site.yml
This adds most of the utilities needed for testing on Windows. The
existing test download the zip file, extract it, install Packetbeat
and Topbeat as services, start them, check that they produce output
(without yet checking anything in the output), stop them and remove
the services at the end.
There are lots of Powershell files which workaround missing Ansible
support for windows. I.E. common modules like sleep, replace, run
are implemented in ps1 scripts.
=> Windows testing support

README.md, Vagrantfile, hosts, roles/test-linux-binary/tasks/main.yml, roles/test-packetbeat-file/tasks/main.yml, roles/test-topbeat-file/tasks/main.yml, roles/test-win-packetbeat-file/tasks/main.yml, roles/test-win-topbeat-file/tasks/main.yml, run-settings-1.0.0-beta3.yml, run-settings-nightly.yml
I had the issue that tests that didn't work were reported as successful
because an old correct file was lying around. This should fix this case.
Also:
* Added some executing instructions to the README
* Added centos7 as test target
=> Make sure output directory is empty before tests.

roles/test-filebeat-file/tasks/main.yml, roles/test-filebeat-file/templates/filebeat.yml, roles/test-linux-binary/tasks/main.yml, roles/test-linux-binary/templates/filebeat.yml, roles/test-linux-binary/templates/packetbeat.yml, roles/test-linux-binary/templates/topbeat.yml, roles/test-packetbeat-file/tasks/main.yml, roles/test-packetbeat-file/templates/packetbeat.yml, roles/test-topbeat-file/tasks/main.yml, roles/test-topbeat-file/templates/topbeat.yml, roles/test-topbeat-file/topebeat.yml, run-settings-1.0.0-beta4.yml
The tests used to do regexp replaces in the default configuration
files, most of which fail now because the config files changed
quite a lot in this release.
I changed the approach here and now we provide a minimal
configuration file for each test.
Tested to work on the linux distros and OS X. Windows still giving me headaches.
=> Update the beats-tester tests for the new configuration files

Vagrantfile, roles/test-filebeat-file/templates/filebeat.yml, roles/test-topbeat-file/tasks/main.yml, run-settings-1.0.0-rc1.yml
Also:
* Fixed an issue with the topbeat test on Darwin
* Removed the tester-es machine which is currently not used.
* Specify a single monitored file on OSX to make tests more stable
=> Add the RC1 testing config

roles/test-filebeat-file/templates/filebeat.yml, roles/test-install/files/mv.ps1, roles/test-install/files/unzip.ps1, roles/test-install/tasks/main.yml, roles/test-linux-binary/tasks/main.yml, roles/test-linux-binary/templates/filebeat.yml, roles/test-linux-binary/templates/packetbeat.yml, roles/test-linux-binary/templates/topbeat.yml, roles/test-packetbeat-file/templates/packetbeat.yml, roles/test-topbeat-file/tasks/main.yml, roles/test-topbeat-file/templates/topbeat.yml, roles/test-topbeat-file/topebeat.yml, roles/test-win-filebeat-file/files/filebeat.yml, roles/test-win-packetbeat-file/files/packetbeat.yml, roles/test-win-topbeat-file/files/topbeat.yml, run-settings-nightly.yml
When using `version: 1.2.0-nightlylatest` the tests fail because the tar and zip files associated with that version actually contain a directory named after the true nightly version number (i.e. packetbeat-1.2.0-nightly160104123543-windows/). The playbooks expect that after extracting the archive that a directory named `packetbeat-1.2.0-nightlylatest-windows/` will exist. 
- The PR changes the archive extraction behavior so that the playbook can always find the extracted directory.
- It also removes any references to `enabled: true/false` from config files.
I tested the changes with versions `1.2.0-nightlylatest`, `1.1.0-SNAPSHOT`, and `1.0.1`.
=> Change to allow 'make nightlies' to work

Vagrantfile, roles/common/tasks/main.yml, roles/test-linux-binary/tasks/main.yml, roles/test-win-winlogbeat-file/files/replace.ps1, roles/test-win-winlogbeat-file/files/run_script.ps1, roles/test-win-winlogbeat-file/files/sleep.ps1, roles/test-win-winlogbeat-file/tasks/main.yml, roles/test-win-winlogbeat-file/vars/main.yml, site.yml
This PR adds a test case for Winlogbeat. Similar to the other tests, it will
- download Winlogbeat,
- install it as a service,
- modify the provided config file with sed like commands (this differs from the other Beat tests on Windows because they run with a templated config file rather than the one provided in the zip),
- start the service,
- sleep while it reads some events,
- verify that at least one event was read and that it has the required fields,
- verify that a log file exists,
- and verify that a registry file exists and has `event_logs` in it.
This depends on the elastic/beats#622 PR to change the `.yaml` to `.yml`. It will need a retest after that change merges and the nightlies are updated.
Closes #19
=> Add Winlogbeat test case

roles/test-win-winlogbeat-file/tasks/main.yml
`count` was removed in elastic/beats#1218.
=> Update Winlogbeat test to not expect count because it was removed

roles/common/tasks/main.yml
This updates the URLs used by beats-tester to get the Windows binaries.
Once we have the 64-bit version of Packetbeat working. We should update beats-tester to test both 32-bit and 64-bit on Windows.
=> Update Windows URLs to include architecture (-32).

roles/common/tasks/main.yml, roles/test-install/tasks/main.yml, site.yml
Implements #32 
It adds a fair bit of duplication in the playbook. If you have suggestions to avoid the duplication please let me know.
This depends on elastic/beats#1276.
=> Add testing of 64-bit binaries.

roles/test-win-packetbeat-file/files/sleep.ps1, roles/test-win-winlogbeat-file/tasks/main.yml, roles/test-win-winlogbeat-file/templates/winlogbeat.yml
- Use a config template for Winlogbeat instead of find/replace on the supplied config file. The template is stored in beats-tester and does not include the Elasticsearch template options that are currently causing the test failure because they were not being commented out.
- Fix a bug that occurs when validating the JSON output of Winlogbeat that contains non-ASCII
characters like a right apostrophe.
=> Fix failing Winlogbeat test case due to uncommented template config

roles/common/tasks/main.yml, roles/common/vars/main.yml, roles/test-linux-binary/tasks/main.yml, roles/test-packetbeat-file/tasks/main.yml, run-settings-1.0.0.yml, run-settings-1.0.1.yml, run-settings-1.1.0-SNAPSHOT.yml, run-settings-1.1.0-latest.yml, run-settings-1.1.0.yml, run-settings-1.1.1-SNAPSHOT.yml, run-settings-1.1.1.yml, run-settings-1.1.2.yml, run-settings-1.2.0-SNAPSHOT.yml, run-settings-1.2.0-latest.yml, run-settings-1.2.0.yml, run-settings-5.0.0-SNAPSHOT.yml, run-settings-5.0.0-alpha1.yml, run-settings-5.0.0-alpha1SNAPSHOT.yml, run-settings-5.0.0-alpha2.yml, run-settings-5.0.0-alpha3-SNAPSHOT.yml, run-settings-5.0.0-alpha3.yml, site.yml
Change the expected filenames for the packages.
Also:
* Cleanups old settings files, adds 5.0.0-alpha3 settings files
* Actually check the results for metricbeat in the binary tests
=> Adjust for new filenames

roles/common/tasks/main.yml, roles/common/vars/main.yml, site.yml
This is needed because of the changes in elastic/beats#1865.
=> Use x86_64 instead of x64

roles/test-linux-binary/templates/metricbeat.yml, roles/test-metricbeat-file/tasks/main.yml, roles/test-metricbeat-file/templates/metricbeat.yml
Load has its own metricset now, so it needs to be enabled.
=> Fixed tests for metricbeat changes

roles/common/tasks/download.yml, roles/test-linux-binary/tasks/main.yml, run-settings-staging.yml
The SHA files format was different. This should be merged roughly at the same time with https://github.com/elastic/beats/pull/2372 which is the packer part of this change.
=> Testing changes for the unified build

roles/test-filebeat-file/tasks/main.yml, roles/test-linux-binary/tasks/main.yml, roles/test-metricbeat-file/tasks/main.yml, roles/test-packetbeat-file/tasks/main.yml
Now that we can easily overwrite config settings with -E, we can use the
default configs in the packaging tests. This has the advantage that we test the
default configuration files.
This PR does this for Linux and Darwin. For Windows we need a slightly
different approach, because the tests start the beats as services, so we don't
control the flags.
=> Test default configurations

roles/test-linux-binary/tasks/main.yml, roles/test-metricbeat-file/templates/metricbeat.yml, roles/test-win-metricbeat-file/files/metricbeat.yml, roles/test-win-metricbeat-file/tasks/main.yml, run-nightlies.yml, run-settings-staging.yml
* Set `metricbeat.max_startup_delay: 0` to remove the random sleep in tests
* Increase the Windows timeout for Metricbeat
* Added a nightlies setting file, for easier testing
=> Fix Metricbeat flaky tests (attempt)

roles/test-linux-binary/tasks/main.yml
Remove `-E metricbeat.modules.0.period=1s` from the command used to run
Metricbeat because the module with index 0 does not exist anymore. Module
0 was previously the system module, and that is now configured by the
modules.d/system.yml file.
This PR uses Ansible `lineinfile` to modify the modules.d/system.yml file
to contain `period: 1s` instead of `period: 10s`.
=> Update command to account for module.d setup

roles/common/defaults/main.yml, roles/common/vars/main.yml, roles/test-heartbeat-file/tasks/main.yml, roles/test-install/tasks/main.yml, roles/test-uninstall/tasks/main.yml, site.yml
The name of the package has changed and so has the name of the service.
The contents of the RPM are as follows. Notice that it's `/etc/init.d/heartbeat-elastic` and `/lib/systemd/system/heartbeat-elastic.service`.
```
/etc/heartbeat/fields.yml
/etc/heartbeat/heartbeat.reference.yml
/etc/heartbeat/heartbeat.yml
/etc/init.d/heartbeat-elastic
/lib/systemd/system/heartbeat-elastic.service
/usr/bin/heartbeat.sh
/usr/share/heartbeat/.build_hash.txt
/usr/share/heartbeat/NOTICE
/usr/share/heartbeat/README.md
/usr/share/heartbeat/bin/heartbeat
/usr/share/heartbeat/bin/heartbeat-god
/usr/share/heartbeat/scripts/migrate_beat_config_1_x_to_5_0.py
```
=> Update heartbeat service name to heartbeat-elastic

.gitignore, Makefile
This eliminates updating the user's real `~/.ssh/config` file, and will also keep all changes local to the Jenkins workspace when testing. I've also ensured that Git will ignore any of these temporary `ssh_config` files, which should not pollute the repository.
=> Use a local ssh_config file for Ansible -> VM connectivity

Vagrantfile
This prevents exposing forwarded ports across all interfaces on the host machine.
=> Bind forwarded ports to the localhost address

Vagrantfile
The original source has since been removed so a copy of the box was taken from a developer machine and preserved on S3.
=> Point Debian 6 Vagrant base box URL to our copy in S3

roles/test-filebeat-file/tasks/main.yml, roles/test-metricbeat-file/tasks/main.yml, run-settings-staging.yml
I already did this fixes for beta1, but forgot to open the PR. They are needed for the macos part of the tests to pass.
=> Fix macos tests for beta1/beta2

.gitignore, roles/common/tasks/download.yml, roles/test-linux-binary/tasks/main.yml, run-settings-staging.yml
Starting with RC1, we publish sha512 files instead of sha1 files. This
updates beats-tester for that change.
=> Update to use sha512

.gitignore, roles/common/tasks/download.yml, roles/test-install/tasks/main.yml, roles/test-linux-binary/tasks/main.yml, run-settings-staging.yml
This seems to be required to get it working on staged builds, which
contain signatures. Better would be to actually import the GPG sig, but
we currently don't do that for other platforms either.
This sits on top of #63, only the second commit is part of this one.
=> Zypper ignore gpg sig (Suse)

Vagrantfile, hosts
Amazon Linux shows up as RedHat in ansible so no changes were required
to the tests, and they all pass.
=> Add support for testing Amazon Linux

.gitignore, roles/common/tasks/download.yml, roles/test-linux-binary/tasks/main.yml, run-settings-staging.yml
The format changed, so updating the tests. Also excluding log files via `.gitignore`.
=> Update format of sha512 files

.gitignore, Makefile, README.md, Vagrantfile, requirements.txt, roles/common/tasks/main.yml, roles/test-install/tasks/main.yml, roles/test-linux-binary/tasks/main.yml, roles/test-metricbeat-file/tasks/main.yml, roles/test-packetbeat-file/tasks/main.yml, roles/test-win-filebeat-file/tasks/main.yml, roles/test-win-heartbeat-file/tasks/main.yml, roles/test-win-metricbeat-file/tasks/main.yml, roles/test-win-packetbeat-file/tasks/main.yml, roles/test-win-winlogbeat-file/tasks/main.yml, run-nightlies.yml, run-settings-released.yml, run-settings-snapshot.yml, run-settings-staging.yml, site.yml
- Add virtualenv for running Ansible in a reproducible manner.
- Change regex for matching Metricbeat output from the system-cpu metricset
The order of the JSON keys in the `metricset` object is different in the output than before (I haven't determined why.)
- Update the win_copy dest argument to include the file name and not just the destination directory.
- Refactor the Makefile and update the README.
- Temporarily disable Filebeat testing https://github.com/elastic/beats/issues/6145 is resolved.
- Fix deprecations (sudo -> become, always_run -> check_mode = no).
- Use ubuntu/precise32 instead of hashicorp/precise32. The hashicorp/precise32 is `ansible_os_family == Mandrake` and none of the Ansible roles handle Mandrake (they expect Debian).
- Add workaround for an Ansible issue on …
=> Fix failing tests

Makefile
The bug leading to this tests being disabled ( elastic/beats#6145 ) is fixed now
=> Re-enable windows filebeat tests

roles/test-metricbeat-file/tasks/main.yml
The order was changed to reflect what happens in 6.2, but we still need
to test older releases (e.g 6.1.x), so changing the regexp to accept both
ways.
=> Allow for different JSON order

Makefile
Add OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES to the environment to
workaround an issue with running Ansible on MacOS 10.13 (High Sierra).
See https://github.com/ansible/ansible/issues/32499
=> Add High Sierra workaround

roles/test-beat/tasks/common/assert.yml, roles/test-beat/tasks/win32nt/assert.yml
This PR includes assertions which check if a Beat has an ephemeral ID in its monitoring event.
If a Beat has an ephemeral ID, it can be shown in XPack Monitoring. (It's still possible that some metrics are not available, due to the lack of CGO.)
Required by https://github.com/elastic/beats/pull/6501
=> Check ephemeral ID of every Beat

roles/test-beat/tasks/common/assert.yml, roles/test-beat/tasks/win32nt/assert.yml
A few metrics were renamed in https://github.com/elastic/beats/pull/6449
This PR follows up the changes in counter names.
I also added debug "messages", so it's visible if something is missing from the event.
@andrewkroh Is it possible to run this branch in Jenkins before merging it?
=> Follow up metrics renames in monitoring events && add debug messages

roles/test-beat/tasks/common/assert.yml, roles/test-beat/tasks/darwin/main.yml, roles/test-beat/tasks/linux/main.yml, roles/test-beat/tasks/main.yml, roles/test-beat/tasks/win32nt/assert.yml, roles/test-beat/tasks/win32nt/main.yml, roles/test-beat/templates/auditbeat.yml.j2, roles/test-beat/templates/filebeat.yml.j2, roles/test-beat/templates/heartbeat.yml.j2, roles/test-beat/templates/metricbeat.yml.j2, roles/test-beat/templates/packetbeat.yml.j2, roles/test-beat/templates/winlogbeat.yml.j2
Instead of using the "Total non-zero metrics" log lines use the HTTP /stats endpoint to fetch metrics. The main benefit is that zero value metrics are not filtered. This allows the tests to assert that the metrics actually exist.
A side-effect of not using logs is that we lose a check that the beat truly shut down. We should add another assertion to check for "\<beatname\> stopped." in the logs.
// cc: @kvch FYI re https://github.com/elastic/beats-tester/pull/74#issuecomment-373073675
=> Use /stats to fetch metrics instead of logs

roles/test-beat/tasks/common/assert.yml, roles/test-beat/tasks/win32nt/assert.yml, site.yml
- Run detailed auditbeat tests on >= 6.2 (where Auditbeat was made GA). The basic smoke test is still run for earlier releases.
- Run monitoring metric assertions on >= 6.3.
=> Add conditionals based on beat version

site.yml
Follow up to #77 where I forgot to add version checks for Auditbeat
testing on Windows.
=> Add conditional for auditbeat on windows

roles/test-linux-binary/tasks/main.yml
It was 10s by default, but the timeout was 5s.
=> Fix test: poll every 1s for heartbeat tests

run-settings-nightlies.yml
With the migration of beats-ci to GCP, we've started pushing these artifacts into a GCS bucket instead of S3.
=> Update snapshot download URL to GCS bucket

run-settings-nightlies.yml
The old `https://storage.cloud.google.com/[BUCKET_NAME]/[OBJECT_NAME]` URL structure is what allows for access control, so it requires authentication with a Google account in order to generate temporary/expiring links (even for public objects).
The new `https://storage.googleapis.com/[BUCKET_NAME]/[OBJECT_NAME]` URL structure should work for public objects without requiring authentication.
See: https://cloud.google.com/storage/docs/collaboration#browser
=> Use the publicly readable URL for snapshot downloads

roles/test-beat/tasks/packetbeat/assert.yml
Only the Packetbeat tests were checking for the presence of the
`beat` field. In 7.0 that field is changing to `agent` so let's
just remove that check. If we need it we can add it back in a
common location that will apply to all Beats.
=> Remove assertion beat field from Packetbeat

roles/test-beat/templates/filebeat.yml.j2
The error was:
Exiting: 1 error: setting 'filebeat.prospectors' has been removed
`prospectors` was deprecated in 6.3 and replaced with `inputs`. In 7.0 it
cannot be used.
=> Update Filebeat config to remove filebeat.prospectors

roles/test-linux-binary/tasks/main.yml
Workaround for https://github.com/elastic/go-sysinfo/issues/28.
Tracked in https://github.com/elastic/beats-tester/issues/97.
=> Disable add_host_metadata on Debian 6

Makefile, Vagrantfile, hosts
debian6 (squeeze) is no on our support matrix for Beats so remove it.
debian8 (jessie) is on the support matrix so add it.
Fixes #100
=> Remove debian6, Add debian8

README.md, roles/test-beat/templates/auditbeat.yml.j2
Enable all metricsets on Linux and only [host, process] on non-Linux.
This does not add any assertions as to the behavior of the module. So this will only
verify that Auditbeat actually runs with the module enabled. Some detailed assertions
can be added later.
=> Test auditbeat system module in 7.0

roles/test-beat/templates/auditbeat.yml.j2
We had a >= 7.0 version restriction on the system module config, but it's available in >= 6.6.
=> Test auditbeat system module on >= 6.6

roles/test-beat/tasks/common/assert.yml
New check for all beats:
- If package is oss: checks that help enroll fails.
- If package is x-pack: check that help enroll doesn't fail.
This test is put to prevent cases where the wrong binary is packaged (i.e. the oss binary in the x-pack distribution).
Test only works on 6.5+ due to the enroll command being first available in v6.5.0.
=> Check that Beat ships with the right binary

roles/common/defaults/main.yml, roles/test-install/tasks/main.yml
This PR includes two fixes to RPM/DEB install and uninstall:
- OSS Beat is never uninstalled when testing Linux packages. 
Uninstall of Beats packages are performed using `{beat_name}-oss` as package name.
However, both the Elastic and OSS distributions of Beats use {beat_name} as the package name. The `-oss` prefix is not used neither in DEB nor in RPM packages.
- Installation of the OSS package under Suse installs the wrong package due to zypper peculiarities.
Zypper, Suse's package manager, has some funny behavior when asked to install an RPM file. Instead of installing it, it will read its package name and version and then fetch the package from one of its repos.
As {beatname}-oss.rpm uses {beatname} as internal package name, trying to install an OSS rpm file will result in the …
=> Fix Linux package install and uninstall

roles/test-beat/templates/auditbeat.yml.j2
Since https://github.com/elastic/beats/issues/10018, the Auditbeat System module uses `datasets` instead of `metricsets` to configure its sub-modules. This reflects that change and fixes the [current CI failures](https://beats-ci.elastic.co/job/elastic+beats-tester+master/242/) for beats-tester on Windows.
=> Auditbeat System module: Change metricsets to datasets

roles/test-beat/vars/filebeat.yml, run-settings-nightlies.yml, run-settings-released.yml, run-settings-snapshot.yml
The registry path changed in https://github.com/elastic/beats/pull/10504.
=> Update registry path for 7.0

roles/test-beat/tasks/winlogbeat/assert.yml
Most core Winlogbeat fields were renamed for ECS so the assertions
needed to be updated.
Fixes #111
=> Update Winlogbeat assertions for 7.x

roles/test-beat/tasks/auditbeat/pre-run.yml
The system/socket dataset needs the tracefs to be mounted.
=> Ensure tracefs or debugfs is mounted for Auditbeat

Vagrantfile
The system/socket dataset in Auditbeat needs features that are in the CentOS 6.9 kernel.
=> Use CentOS 6.9 for Auditbeat system/socket testing

roles/test-beat/tasks/auditbeat/pre-run.yml
Add a conditional statement so that mounting debugfs/tracefs only happens on Linux.
=> Exclude Windows from mounting tracefs/debugfs

Vagrantfile
This fixes these warnings:
```
[WARNING]: Updating cache and auto-installing missing dependency: python-apt
[WARNING]: Could not find aptitude. Using apt-get instead
```
=> Fix apt warnings

roles/test-install/tasks/main.yml
This fixes this warning:
```
[WARNING]: Consider using the yum, dnf or zypper module rather than running 'rpm'.  If you need to use command because yum, dnf or zypper is insufficient you can add 'warn: false' to this command task or set 'command_warnings=False' in ansible.cfg to get rid of this message.
```
=> Fix warnings for rpm command

Vagrantfile
The original port (2413) conflicts with Ubuntu 18.04. 🙅
=> Fix ssh port for Ubuntu 20.04

Vagrantfile, hosts
I'm seeing this error on the Ubuntu 20.04 box.  I'd like to revert this until I can figure it out.
```08:14:57 Vagrant was unable to mount VirtualBox shared folders. This is usually
08:14:57 because the filesystem "vboxsf" is not available. This filesystem is
08:14:57 made available via the VirtualBox Guest Additions and kernel module.
08:14:57 Please verify that these guest additions are properly installed in the
08:14:57 guest. This is not a bug in Vagrant and is usually caused by a faulty
08:14:57 Vagrant box. For context, the command attempted was:
08:14:57 
08:14:57 mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant
08:14:57 
08:14:57 The error output from the command was:
08:14:57 
08:14:57 : No such device```
=> Revert Ubuntu 20.04 support

Vagrantfile, hosts
- I disabled synced folders for Ubuntu 20.04
- `python-minimal` does not exist for Ubuntu `20.04`, but we're already installing `python2.7`.
=> Add support for Ubuntu 20.04

Vagrantfile, hosts
Originally when we added RHEL 8, CentOS 8 was not available.  Since CentOS 8 is out, I feel like we should switch for consistency.  We already have CentOS 6 and 7.
=> Switch from RHEL 8 to CentOS 8

.ci/jobs/beats-tester-mbp.yml, .ci/jobs/defaults.yml
This is the very first approach to enable the CI pipeline in beats-ci.elastic.co using the JJBB.
Caused by https://github.com/elastic/beats-tester/issues/155
=> [jjbb]: elastic/beats-tester repo

.ci/Jenkinsfile, Makefile, ansible.cfg, requirements.txt, roles/test-install/tasks/main.yml, roles/test-uninstall/tasks/main.yml
- Enable CI Pipeline for any changes related to Pull Requests, branches or tags in this repo
- Supports JUnit reporting (see [ansible-junit-callback](https://docs.ansible.com/ansible/latest/plugins/callback/junit.html)) 
- Add retries/sleeps when running ansible tasks to install/uninstall packages since the metadata repos might be not accessible as I've already seen in a couple of test runs.
It will help us to test things in the CI (such as: upgrade the ansible version)
Depends on https://github.com/elastic/beats-tester/pull/156
- parallel stages to avoid the over 2 hours run build -> for instance [this](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats-tester-mbp%2FPR-157/detail/PR-157/3/pipeline)
The parallel setup is not the one defined in the Makefile but in the CI …
=> [ci]: MultiBranchPipeline

.ci/Jenkinsfile
See if the below stacktrace error gets resolved
```
11:23:22  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
11:23:22  Makefile:17: recipe for target 've/bin/activate' failed
11:23:22  make[1]: *** [ve/bin/activate] Error 1
11:23:22  make[1]: Leaving directory '/var/lib/jenkins/workspace/Beats_beats-tester-mbp_master/src'
11:23:22  Makefile:29: recipe for target 'batch' failed
11:23:22  make: *** [batch] Error 1
```
=> [CI] force Python to use UTF-8 by default

.ci/Jenkinsfile
This a follow up for https://github.com/elastic/beats-tester/pull/162
=> [CI] enable slack notifications for build failures in branches/tags

roles/test-beat/vars/filebeat.yml
The registry path changed in https://github.com/elastic/beats/pull/19633
Otherwise:
```
Error
file not found: /var/lib/filebeat/registry/filebeat/data.json
Stacktrace
{
"changed": false, 
"msg": "file not found: /var/lib/filebeat/registry/filebeat/data.json"
}
```
```
$ cat run-settings-jenkins.yml 
beats_url_base: https://snapshots.elastic.co/8.0.0-7025cc53/downloads/beats
apm_url_base: https://snapshots.elastic.co/8.0.0-7025cc53/downloads/apm-server
version: 8.0.0-SNAPSHOT
$ RUN_SETTINGS=jenkins GROUPS=sles make batch
...
PLAY RECAP *************************************************************************************************************************************************************************************************
tester-sles12-64           : ok=382  changed=176  unreachable=0 …
```
=> Update registry path for 7.9

Vagrantfile
```
[2020-09-02T16:54:12.096Z] The box 'ubuntu/precise32' could not be found or
[2020-09-02T16:54:12.096Z] could not be accessed in the remote catalog. If this is a private
[2020-09-02T16:54:12.096Z] box on HashiCorp's Vagrant Cloud, please verify you're logged in via
[2020-09-02T16:54:12.096Z] `vagrant login`. Also, please double-check the name. The expanded
[2020-09-02T16:54:12.096Z] URL and error message are shown below:
[2020-09-02T16:54:12.096Z] 
[2020-09-02T16:54:12.096Z] URL: ["https://vagrantcloud.com/ubuntu/precise32"]
[2020-09-02T16:54:12.096Z] Error: The requested URL returned error: 404 Not Found
```
Build successfully downloaded the vagrant box
```
==> tester-ubuntu1204-32: Successfully added box 'hashicorp/precise32' (v1.0.0) for 'virtualbox'!
[2020-09-03T08:49:26.780Z] ==> …
```
=> The box 'ubuntu/precise32' could not be found

.ci/Jenkinsfile
Change the location where the vagrant boxes are cached to the default HOME/.vagrant.d.
This will speed up the builds since the boxes will be already cached.
```
[2020-09-04T10:48:28.004Z] 
...
Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
....
[2020-09-04T10:56:12.985Z] ==> tester-awslinux2: Successfully added box 'gbailey/amzn2' (v20200825.0.0) for 'virtualbox'!
...
```
=> Use cached folder with the vagrant boxes

Makefile, README.md
This is a cherry-pick from the open PR: https://github.com/elastic/beats-tester/pull/158
Generate the matrix table of support with some automation
`make markdown-matrix` will return the table of supported OS versions that are tested when running the beats-tester
See https://github.com/elastic/beats-tester/pull/178/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8
=> [DOCS] Update OS matrix support

.ci/Jenkinsfile
As long as we got only one worker and there are events regarding when to run the beats-tester we need to be a bit relax with the timeouts
=> [ci] increase timeout

Vagrantfile
Since virtualBox cannot create more 128 host-only interfaces and those interfaces are not removed in Vagrant by default
Let's force the configuration in vagrant to remove those interfaces as explained in [here](https://github.com/hashicorp/vagrant/blob/b886ec0b323163920202baec6424b64ccfcc56bc/plugins/providers/virtualbox/config.rb\#L29-L35)
Closes #177
I ssh onto one of the boxes and no interfaces were left:
```
Last login: Wed Oct  7 13:54:04 2020 from 35.205.119.111
vmartinez@worker-1244230:~$ ifconfig -a | grep vboxnet | tail
vboxnet0  Link encap:Ethernet  HWaddr 0a:00:27:00:00:00  
```
=> Fix cannot allocate memory

.ci/trigger-builds.groovy
Use packaging approach that has been implemented with https://github.com/elastic/beats/pull/21169
Therefore this particular event-triggers is only looking after BCs
=> [CI] avoid duplicated builds

.ci/Jenkinsfile, packages.yml
When empty params then groovy exception
```
11:03:49  GitHub has been notified of this commit’s build result
11:03:49  
11:03:49  Also:   groovy.lang.MissingPropertyException: No such property: APM_URL_BASE for class: groovy.lang.Binding
11:03:49  Also:   groovy.lang.MissingPropertyException: No such property: APM_URL_BASE for class: groovy.lang.Binding
11:03:49  Also:   groovy.lang.MissingPropertyException: No such property: APM_URL_BASE for class: groovy.lang.Binding
11:03:49  groovy.lang.MissingPropertyException: No such property: APM_URL_BASE for class: groovy.lang.Binding
11:03:49  	at groovy.lang.Binding.getVariable(Binding.java:63)
11:03:49  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:270)
11:03:49  	at …
```
=> [CI] fix No such property: APM_URL_BASE

Vagrantfile
> CentOS Linux 6 EOL
As has been announced everywhere for the past year (and more!) CentOS 6 has been moved to End Of Life (EOL) status as of November 30th, 2020. During the first week in December 2020, the 6.10 directory will move to vault.centos.org
> Packages will still be available at: http://vault.centos.org/centos/6.10/. However, once moved, there will be no more updates pushed to vault.centos.org. Therefore, security issues will no longer be fixed.
Closes https://github.com/elastic/beats-tester/issues/187
=> Fix CentOS 6 EOL package URL

roles/common/tasks/download.yml
I think set_fact could be colliding with multiple lookups for different beats
and a mismatch is occuring when the validation happens
For example, when doing parallel deploys, set_fact may be a global state thing and could contain the incorrect beat_sha512 variable for the package being downloaded
ref:https://github.com/elastic/observability-robots/issues/579
Signed-off-by: Adam Stokes <51892+adam-stokes@users.noreply.github.com>
=> Attempting to scope the checksum within the download role

packages.yml, roles/common/tasks/download.yml
This should fully resolve https://github.com/elastic/observability-robots/issues/579 and is the correct fix for https://github.com/elastic/beats-tester/pull/202
The problem here turned out to be that GCE aggressively sets cache-control headers on objects resulting in Ansible downloading incorrect checksum data. 
In ad-hoc testing, I varying times for this cache expiration for a bucket that was configured in a similar way to the current artifact bucket but some of them were as low as ~5 minutes, which would explain why this problem presents itself as a race condition. This pipeline is typically run downstream of the main APM Server pipeline which means that we're racing the cache expiration.
This fix works around the issue by simply passing in the `ignoreCache=1` flag to all requests to …
=> Force no-cache on artifact requests

roles/common/tasks/download.yml
The previous attempt to fix this issue [was not successful](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-check-packages-mbp/detail/master/742/pipeline/92). 
We're going to try again but this time set the cache-control header [using the Ansible option](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/url_lookup.html).
=> Use force=True for cache-control

README.md
If running the ansible playbook with python 3.9 then
```
"/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.TextIOWrapper' object
make: *** [ansible-playbook-run-elastic] Error 250
```
See https://github.com/ansible/ansible/issues/63973#issuecomment-546967422
=> Update docs with the requirements to run the ansible playbook

.ci/Jenkinsfile
Error
```
21:42:58  hudson.remoting.ProxyException: org.kohsuke.github.HttpException: {"message":"Validation Failed","errors":[{"resource":"Status","code":"custom","message":"This SHA and context has reached the maximum number of statuses."}],"documentation_url":"https://docs.github.com/rest/commits/statuses#create-a-commit-status"}
21:42:58  	at org.kohsuke.github.GitHubConnectorResponseErrorHandler$1.onError(GitHubConnectorResponseErrorHandler.java:56)
21:42:58  	at org.kohsuke.github.GitHubClient.detectKnownErrors(GitHubClient.java:424)
21:42:58  	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:386)
21:42:58  	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:355)
21:42:58  	at org.kohsuke.github.Requester.fetch(Requester.java:76)
21:42:58  	at …
```
=> ci: trying to fix some issues with reached limited number of git commit status

.ci/Jenkinsfile
`    issueCommentTrigger('(?i).*(?:jenkins\\W+)?run\\W+(?:the\\W+)?tests(?:\\W+please)?.*')` was about 3 years old but we moved to use something else across all the projects so we didn't need to hardcode the same string in each Jenkinsfile.
=> ci: use standard github commands (/test)
