roles/kibana/files/install-kibana.sh, roles/kibana/files/kibana.init.debian, roles/kibana/files/kibana.yml, roles/kibana/handlers/main.yml, roles/kibana/tasks/main.yml, roles/kibana/vars/main.yml, run-settings-nightly.yml, site.yml
=> Kibana role

roles/test-filebeat-file/tasks/main.yml
"text" field was renamed to "message", so reflect that in the test
=> Fix text with the latest beta4

Makefile, Vagrantfile
Set v.gui to false so windows can also boot up under linux
Add cleanup command to make sure all tests are run in a clean environment
=> Fix Linux issue

Makefile, run-settings-1.0.0-beta2.yml, run-settings-1.0.0-beta3.yml, run-settings-1.0.0-beta4.yml, run-settings-1.0.0-rc1.yml, run-settings-1.0.0-rc2.yml, run-settings-1.0.0.yml, run-settings-1.0.1.yml, run-settings-1.1.0-SNAPSHOT.yml, run-settings-1.1.0-latest.yml, run-settings-1.1.0.yml, run-settings-1.2.0-latest.yml
The goal is to use these commands for jenkins
=> Enhanced run settings

.gitignore, roles/test-linux-binary/tasks/main.yml
Automatically checks the version number of each build if it is correct.
=> Check version number of build

roles/test-win-winlogbeat-file/tasks/main.yml
See elastic/beats#689 for details of the field renames.
=> Updating Winlogbeat test for the renamed fields

roles/test-linux-binary/templates/packetbeat.yml, roles/test-packetbeat-file/templates/packetbeat.yml, roles/test-win-packetbeat-file/files/packetbeat.yml, run-settings-5.0.0-SNAPSHOT.yml, run-settings-5.0.0-alpha2.yml
And added settings file for alpha2.
=> Adjusted Packetbeat configs

run-settings-5.0.0-alpha3-SNAPSHOT.yml, run-settings-5.0.0-alpha3.yml, run-settings-staging.yml
also cleaned up old release files.
=> Updated staging URL

roles/test-install/tasks/main.yml, run-settings-staging.yml
Make sure an already installed version is not interfering with the tests.
=> Uninstall deb/rpm before testing

roles/test-install/files/unzip.ps1, roles/test-install/tasks/main.yml, roles/test-win-filebeat-file/tasks/main.yml, roles/test-win-heartbeat-file/tasks/main.yml, roles/test-win-metricbeat-file/tasks/main.yml, roles/test-win-packetbeat-file/tasks/main.yml, roles/test-win-winlogbeat-file/tasks/main.yml
Tested with Ansible 2.3.1.0 which is what [beats-ci](https://beats-ci.elastic.co/job/elastic+beats-tester+master/) is using.
=> Updates to work with Ansible 2

Vagrantfile, hosts, roles/common/tasks/download.yml, roles/common/tasks/main.yml, roles/test-filebeat-file/tasks/main.yml, roles/test-heartbeat-file/tasks/main.yml, roles/test-install/tasks/main.yml, roles/test-metricbeat-file/tasks/main.yml, roles/test-packetbeat-file/tasks/main.yml, roles/test-uninstall/tasks/main.yml, run-nightlies.yml
This solves elastic/beats#737. No changes to the Beats were required
for the tests to pass, only changes in beats-tester.
=> Add opensuse and ubuntu 16.04 to the target systems

README.md, Vagrantfile, hosts, packages.yml, roles/test-beat/tasks/main.yml, roles/test-beat/tasks/unsupported.yml, run-settings-released.yml
Uses the image from https://app.vagrantup.com/elastic/boxes/sles-12-x86_64.
Closes #83
=> Add SLES12 to beats-tester

roles/test-beat/tasks/common/assert.yml, roles/test-beat/tasks/linux/assert.yml
=> Check new file handle metrics

README.md
Add requirements and an example command for macOS X.
=> Add a list of requirements for 5.x

roles/test-beat/templates/auditbeat.yml.j2
We added these metricsets in 6.7.
=> Enable package and login metricset

roles/test-install/tasks/main.yml, roles/test-uninstall/tasks/main.yml
Add lock_timeout for yum to address these issues:
- https://github.com/elastic/beats-tester/issues/127
- https://github.com/ansible/ansible/issues/57189
=> Add lock_timeout for yum

requirements.txt
Here are the details on the CVE:
https://nvd.nist.gov/vuln/detail/CVE-2019-10156
=> Update to latest ansible to fix potential security vulnerability

requirements.txt
Bug fixes:
https://github.com/ansible/ansible/blob/stable-2.8/changelogs/CHANGELOG-v2.8.rst#v2-8-5
=> Update ansible to 2.8.5

.ci/Jenkinsfile
This will help to debug what's going when one of the batches failed.
=> [CI] run in parallel

.ci/Jenkinsfile, .ci/jobs/beats-tester-mbp.yml, .ci/jobs/beats-tester-trigger-builds.yml, .ci/jobs/defaults.yml, .ci/trigger-builds.groovy
MBP is not anymore in charge to trigger builds when:
- on a daily basis if there is a new BC.
- when the upstream project got built successfully.
Simplify the MBP
=> [CI] split trigger pipeline events

.ci/trigger-builds.groovy
Cached artifact should be stored in the daily pipeline instead
=> [CI] Copy from the job itself

roles/common/tasks/download.yml, roles/test-linux-binary/tasks/main.yml
Use `get_url` task with `sha512` validation and include the download in some other roles
DRY
=> Refactor download package with checksum

.ci/Jenkinsfile
Let's notify to the beats team using the same slack message template we also use for the beats project
Provide more visibility what's going on to the right team
=> [notification] standardise slack message and channel

.ci/jobs/beats-tester-trigger-builds.yml
=> [JJBB] Rename title and description

.ci/Jenkinsfile
We got some lack of resources so let's fail fast to be able to launch some other builds.
=> [CI] fail fast stages

.ci/Jenkinsfile
Reverts elastic/beats-tester#186
Since there are more MacOS workers
=> Revert "[CI] fail fast stages"

.ci/jobs/defaults.yml
This is not needed as this project is push based events
=> jjbb: remove periodic

.ci/Jenkinsfile
otherwise, artifacts are not found since they are a bit old
=> bump version 8.7.0
